import type { Metadata } from 'next';
import Link from 'next/link';
import AppFooter from '@/components/AppFooter';

export const metadata: Metadata = {
  title: 'Terms of Service -- Rune',
  description: 'Terms of service for Rune. Your intellectual property stays yours.',
};

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2
      className="mb-4 mt-12 font-serif text-xl"
      style={{ color: 'var(--rune-heading)' }}
    >
      {children}
    </h2>
  );
}

function Paragraph({ children }: { children: React.ReactNode }) {
  return (
    <p
      className="mb-4 text-[15px] leading-relaxed"
      style={{ color: 'var(--rune-text)' }}
    >
      {children}
    </p>
  );
}

function BulletList({ items: listItems }: { items: string[] }) {
  return (
    <ul className="mb-4 ml-5 flex flex-col gap-2">
      {listItems.map((item) => (
        <li
          key={item}
          className="list-disc text-[15px] leading-relaxed"
          style={{ color: 'var(--rune-text)' }}
        >
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh flex-col">
      <div className="mx-auto w-full max-w-2xl flex-1 px-6 py-16">
        <Link
          href="/"
          className="mb-12 inline-flex items-center gap-2 text-sm transition-colors duration-200"
          style={{ color: 'var(--rune-muted)' }}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to Rune
        </Link>

        <p
          className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em]"
          style={{ color: 'var(--rune-gold)' }}
        >
          Terms of Service
        </p>
        <h1
          className="mb-2 font-serif text-3xl"
          style={{ color: 'var(--rune-heading)' }}
        >
          Your book. Your IP. Period.
        </h1>
        <p className="mb-8 text-sm" style={{ color: 'var(--rune-muted)' }}>
          Last updated: March 18, 2026
        </p>

        <div
          className="mb-10 rounded-lg border px-5 py-4"
          style={{
            backgroundColor: 'color-mix(in srgb, var(--rune-gold) 6%, transparent)',
            borderColor: 'color-mix(in srgb, var(--rune-gold) 15%, transparent)',
          }}
        >
          <p
            className="font-serif text-[15px] leading-relaxed"
            style={{ color: 'var(--rune-heading)' }}
          >
            The short version: Everything you create in Rune is 100% yours.
            Your stories, your characters, your worlds, your manuscripts.
            We claim zero ownership over any content you produce. Rune is the
            scribe &mdash; you are the author.
          </p>
        </div>

        <SectionHeading>Intellectual property</SectionHeading>
        <Paragraph>
          This is the most important section. Read it carefully:
        </Paragraph>
        <BulletList
          items={[
            'You own all content you create using Rune. This includes stories, characters, world-building, knowledge base entries, manuscripts, drafts, notes, and any other creative output.',
            'Rune and id8Labs claim no intellectual property rights over your content. Not now, not ever.',
            'You retain full copyright to everything you write, speak, or create through Rune.',
            'You are free to publish, sell, license, adapt, or distribute your work in any way you choose. No attribution to Rune is required.',
            'AI-assisted content (text generated by Claude through Rune) is yours. The AI is a tool you directed. The creative vision, the world, the story -- that\'s yours.',
          ]}
        />
        <Paragraph>
          We built Rune so people can write books. Taking ownership of those
          books would defeat the entire purpose. Your IP is your IP.
        </Paragraph>

        <SectionHeading>What Rune is</SectionHeading>
        <Paragraph>
          Rune is a voice-first writing platform. It provides:
        </Paragraph>
        <BulletList
          items={[
            'Voice-to-text transcription for speaking your ideas.',
            'AI conversation (powered by Claude) to interview you, organize your world, and help you write.',
            'A structured knowledge base that remembers your characters, settings, lore, and timelines.',
            'Manuscript assembly to compile your work into chapters.',
            'A persistent workspace where your creative work lives across sessions.',
          ]}
        />

        <SectionHeading>What Rune is not</SectionHeading>
        <BulletList
          items={[
            'Rune is not a ghostwriting service. Sam helps you structure and write, but the ideas, direction, and creative decisions are yours.',
            'Rune is not a publisher. We help you get to a manuscript. What you do with it is your choice.',
            'Rune is not a content farm. You can\'t use Rune to mass-produce content for spam, deception, or plagiarism.',
            'Rune does not replace professional editors, agents, or publishers.',
          ]}
        />

        <SectionHeading>Your responsibilities</SectionHeading>
        <BulletList
          items={[
            'You are responsible for the content you create. Don\'t use Rune to produce content that infringes on others\' intellectual property.',
            'If you self-host with your own API keys, you are responsible for keeping them secure.',
            'Don\'t attempt to access other users\' data or circumvent security protections.',
            'Don\'t use Rune to generate harmful, illegal, or deceptive content.',
          ]}
        />

        <SectionHeading>Subscription and pricing</SectionHeading>
        <Paragraph>
          Rune is a subscription service. Your subscription includes all AI
          features &mdash; conversation with Sam, voice transcription,
          knowledge base management, and manuscript assembly. There are no
          hidden API costs or per-token charges. You pay one price, Sam does
          the rest.
        </Paragraph>
        <BulletList
          items={[
            'AI costs (Claude, Deepgram) are included in your subscription. No additional charges.',
            'Subscription details and pricing are shown at signup and in your account settings.',
            'You can cancel at any time. Your data remains accessible for export after cancellation.',
            'If you self-host Rune (open source, MIT), you provide your own API keys and pay providers directly.',
          ]}
        />

        <SectionHeading>Service availability</SectionHeading>
        <Paragraph>
          Rune is provided as-is. We work to keep the hosted version
          (rune-two.vercel.app) available, but we don&apos;t guarantee uptime.
          For maximum reliability and control, self-host using the open source
          Docker setup.
        </Paragraph>

        <SectionHeading>Account termination</SectionHeading>
        <Paragraph>
          You can delete your account at any time from Settings &gt; Account.
          We may terminate accounts that violate these terms (spam, abuse,
          illegal use). Before any termination, we will attempt to notify you
          and give you time to export your data.
        </Paragraph>

        <SectionHeading>Open source</SectionHeading>
        <Paragraph>
          Rune&apos;s source code is available under the MIT license. You can
          fork it, modify it, self-host it, or build on it. The MIT license
          applies to the software. Your content created using the software is
          governed by these terms (i.e., it&apos;s yours).
        </Paragraph>

        <SectionHeading>Changes to these terms</SectionHeading>
        <Paragraph>
          We may update these terms. When we do, we&apos;ll update the date at
          the top. Material changes (especially anything affecting IP ownership)
          will be communicated clearly. We will never retroactively claim rights
          to content you&apos;ve already created.
        </Paragraph>

        <SectionHeading>Governing law</SectionHeading>
        <Paragraph>
          These terms are governed by the laws of the State of Florida, United
          States. id8Labs LLC is a Florida limited liability company.
        </Paragraph>

        <div className="mt-16 border-t pt-8" style={{ borderColor: 'var(--rune-border)' }}>
          <p className="text-sm" style={{ color: 'var(--rune-muted)' }}>
            Questions about these terms? Reach out at{' '}
            <a
              href="mailto:eddie@id8labs.app"
              className="transition-colors duration-200"
              style={{ color: 'var(--rune-gold)' }}
            >
              eddie@id8labs.app
            </a>
          </p>
        </div>
      </div>

      <AppFooter />
    </div>
  );
}
