import type { Metadata } from 'next';
import Link from 'next/link';
import AppFooter from '@/components/AppFooter';

export const metadata: Metadata = {
  title: 'Privacy Policy -- Rune',
  description: 'How Rune handles your data, your stories, and your privacy.',
};

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2
      className="mb-4 mt-12 font-serif text-xl"
      style={{ color: 'var(--rune-heading)' }}
    >
      {children}
    </h2>
  );
}

function Paragraph({ children }: { children: React.ReactNode }) {
  return (
    <p
      className="mb-4 text-[15px] leading-relaxed"
      style={{ color: 'var(--rune-text)' }}
    >
      {children}
    </p>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="mb-4 ml-5 flex flex-col gap-2">
      {items.map((item) => (
        <li
          key={item}
          className="list-disc text-[15px] leading-relaxed"
          style={{ color: 'var(--rune-text)' }}
        >
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function PrivacyPage() {
  return (
    <div className="flex min-h-dvh flex-col">
      <div className="mx-auto w-full max-w-2xl flex-1 px-6 py-16">
        <Link
          href="/"
          className="mb-12 inline-flex items-center gap-2 text-sm transition-colors duration-200"
          style={{ color: 'var(--rune-muted)' }}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to Rune
        </Link>

        <p
          className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em]"
          style={{ color: 'var(--rune-gold)' }}
        >
          Privacy Policy
        </p>
        <h1
          className="mb-2 font-serif text-3xl"
          style={{ color: 'var(--rune-heading)' }}
        >
          Your words stay yours.
        </h1>
        <p className="mb-8 text-sm" style={{ color: 'var(--rune-muted)' }}>
          Last updated: March 18, 2026
        </p>

        <div
          className="mb-10 rounded-lg border px-5 py-4"
          style={{
            backgroundColor: 'color-mix(in srgb, var(--rune-gold) 6%, transparent)',
            borderColor: 'color-mix(in srgb, var(--rune-gold) 15%, transparent)',
          }}
        >
          <p
            className="font-serif text-[15px] leading-relaxed"
            style={{ color: 'var(--rune-heading)' }}
          >
            The short version: We don&apos;t read your books. We don&apos;t
            train on your writing. We don&apos;t sell your data. Your stories,
            characters, worlds, and words belong entirely to you.
          </p>
        </div>

        <SectionHeading>What we collect</SectionHeading>
        <Paragraph>
          Rune collects the minimum data needed to give you a working account
          and a persistent writing experience:
        </Paragraph>
        <BulletList
          items={[
            'Email address -- used for sign-in (one-time passcode, no passwords stored).',
            'Display name -- optional, shown in your profile.',
            'Theme preference -- light, dark, or system.',
            'API keys (if you bring your own) -- stored encrypted in your profile, used only for your sessions.',
          ]}
        />

        <SectionHeading>What we store</SectionHeading>
        <Paragraph>
          Everything you create in Rune lives in a Supabase database protected
          by row-level security. This includes:
        </Paragraph>
        <BulletList
          items={[
            'Your books, sessions, and conversation transcripts.',
            'Your knowledge base -- characters, locations, lore, relationships, timelines.',
            'Your workspace files -- brainstorm notes, drafts, manuscript content.',
            'Backlog items generated by Sam during your sessions.',
          ]}
        />
        <Paragraph>
          All of this data is scoped to your account. No other user can see it.
          No Rune employee reads it. It exists to serve your writing and nothing
          else.
        </Paragraph>

        <SectionHeading>What we never do</SectionHeading>
        <BulletList
          items={[
            'We never train AI models on your content. Your writing is not training data.',
            'We never sell, share, or license your data to third parties.',
            'We never read your manuscripts, stories, or conversation transcripts.',
            'We never use your content for marketing, case studies, or examples without your explicit written consent.',
            'We never retain your data after you delete your account.',
          ]}
        />

        <SectionHeading>Third-party services</SectionHeading>
        <Paragraph>
          Rune uses third-party APIs to power voice input and AI conversation.
          When you use these features, your data passes through:
        </Paragraph>
        <BulletList
          items={[
            'Anthropic (Claude API) -- Your conversation text is sent to Claude for responses. Anthropic does not train on API inputs by default. See Anthropic\'s usage policy for details.',
            'Deepgram -- Your voice audio is sent to Deepgram for transcription. Deepgram processes audio in real-time and does not store recordings.',
            'Supabase -- Database hosting and authentication. Data is stored in Supabase-managed PostgreSQL with encryption at rest.',
            'Vercel -- Application hosting. No user content is stored on Vercel.',
          ]}
        />
        <Paragraph>
          If you self-host Rune, you control which services your data touches.
          Bring your own API keys and your own infrastructure.
        </Paragraph>

        <SectionHeading>Data deletion</SectionHeading>
        <Paragraph>
          You can delete your account and all associated data from Settings
          &gt; Account. This permanently removes your profile, all books,
          sessions, knowledge base entries, workspace files, and backlog items.
          This action is irreversible.
        </Paragraph>

        <SectionHeading>Self-hosting</SectionHeading>
        <Paragraph>
          Rune is open source (MIT license) and supports Docker self-hosting.
          When you self-host, your data never touches our servers. You own the
          database, the infrastructure, and the keys. We encourage self-hosting
          for anyone who wants maximum control over their creative work.
        </Paragraph>

        <SectionHeading>Changes to this policy</SectionHeading>
        <Paragraph>
          If we change this policy, we&apos;ll update the date at the top and
          note what changed. We won&apos;t quietly weaken your protections.
        </Paragraph>

        <div className="mt-16 border-t pt-8" style={{ borderColor: 'var(--rune-border)' }}>
          <p className="text-sm" style={{ color: 'var(--rune-muted)' }}>
            Questions? Reach out at{' '}
            <a
              href="mailto:eddie@id8labs.app"
              className="transition-colors duration-200"
              style={{ color: 'var(--rune-gold)' }}
            >
              eddie@id8labs.app
            </a>
          </p>
        </div>
      </div>

      <AppFooter />
    </div>
  );
}
